seed: 2024
comment: bspm_gowalla
device: cuda
batch_size: 1024

dataset: gowalla
metrics: [recall, ndcg]
top_ks: [10, 20]

sharp_solv: rk4
sharp_step: 1
sharp_time: 2.5
ideal_cutoff: 448
ideal_weight: 0.2
early_merge: 1 # True
point_combi: 0 # False
sharp_off: 0 # False