seed: 2024
device: cuda
batch_size: 1024

metrics: [recall, ndcg]
top_ks: [10, 20]

sharp_solv: euler
sharp_step: 1
sharp_time: 1
ideal_cutoff: 256
ideal_weight: 0.3
early_merge: 1 # True
point_combi: 0 # False
sharp_off: 0 # False